spring:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/estoque
    username: postgres
    password: motog
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 711070733155-blqr3jb7559b0m6sjivpoepfcvh5krqk.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
logging:
  level:
    org:
      hibernate:
        org:
          hibernate:
            type:
              descriptor:
                sql:
                  BasicBinder: TRACE
            SQL: DEBUG
